databaseChangeLog:
- changeSet:
    id: 1613410830555-1
    author: hkasch (generated)
    changes:
    - addDefaultValue:
        columnDataType: timestamp
        columnName: evaluation_settings_from
        defaultValue: "1970-01-01 00:00:00"
        tableName: evaluation
