---
title: "Laboraufgabe 2.2"
description: "# Laboraufgabe 2.2\n---\n#### Code - `main.c`:\n - Kommentieren Sie\
  \ alle „fehlerhaften“ Zeilen in folgendem Rumpfprogramm aus\n (der\nBegriff „Fehler“\
  \ umfasst hier Compilerfehler, ggf. Compilerwarnungen und vor\nallem inhaltliche\
  \ Fehler, die nicht notwendig zu Compilerfehlern oder\nCompilerwarnungen führen).\
  \ Begründen Sie, warum es sich jeweils um einen\nFehler handelt und korrigieren\
  \ Sie die entsprechenden Zeilen sinnvoll, so dass\ndas Programm einwandfrei kompiliert\
  \ und inhaltlich (im Sinne von\nVariablendeklarationen und -definitionen) sinnvoll\
  \ ist."
hidden:
- "**/*_test.py"
- ".codeclimate.yml"
- "requirements.txt"
- "headercheck.py"
- "Exercise.txt"
- "args.txt"
protected: []
evaluation:
- step: "junit"
  options:
    commands:
    - "pip install -r requirements.txt"
    - "pytest --junitxml=test-results/TEST-suite.xml main_test.py"
    image: "python:3.7"
    project-path: "/code"
    results-path: "test-results"
  title: "Unit Tests"
- step: "codeclimate"
  options: {}
  title: "Code Quality"
- step: "comments"
  options: {}
  title: "Comments"
